# Generated by Django 4.1.4 on 2023-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('mobno', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('pickup', models.CharField(max_length=200)),
                ('drop', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('mobno', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
